import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/layout/Navbar";
import {
  ClerkProvider,
  SignIn,
  SignUp,
  SignedIn,
  SignedOut,
  // UserButton,
} from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Coinbase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <header></header>
          <main>
            <SignedOut>
              {/*
                Render the SignUp component when the user is signed out
              */}
              <div className="flex justify-center h-screen w-auto place-items-center">
                <SignUp path="path" />
                {/* You can customize the routing here */}
              </div>
            </SignedOut>
            <SignedIn>
              {/* 
                <UserButton />
                You can add User specific content or components here
              */}
              <Navbar />
              {children}
            </SignedIn>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
